apiVersion: apps/v1
kind: Deployment
metadata:
  name: stuck-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stuck-app
  template:
    metadata:
      labels:
        app: stuck-app
    spec:
      containers:
        - name: stuck-app
          image: nginx:1.27
